### ISSUE TITLE
Properly tagged versions

### ISSUE THREAD

**Issue by krnlde** [brian-gates/cypher-stream#17]
I'd recommend tagging your final versions which allows npm and package-managers distinguish semver-updates.

**Comment by brian-gates** [comment]
Not sure I understand what you mean.  Tag them in git?  Doesn't the version in package.json already distinguish semver updates?

**Comment by krnlde** [comment]
I think they are tightly coupled with git. Anyways it is not a bad habit to do that. Since some people want to download snapshots directly rather than via npm.

**Comment by sebinsua** [comment]
Update `package.json` files using [`npm version` and I think the git tag and commit is created automatically for you](https://docs.npmjs.com/cli/version).
